### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by mfeurer** [sfalkner/pySMAC#9]
This happens to me when the target algorithm crashes and no time limit is specified. The full error message is:

```
Traceback (most recent call last):
  File "/home/feurerm/Software/SMAC/pysmac/pysmac/remote_smac.py", line 368, in remote_smac_function
Process Call to your function:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
self._target(*self._args, **self._kwargs)
  File "/home/feurerm/virtualenvs/autosklearn/local/lib/python2.7/site-packages/pynisher/limit_function_call.py", line 76, in subprocess_func
if (res is None) and ((cpu_time > current_t_limit - 2e-2) or
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by sfalkner** [comment]
should be fixed by commit d8ddaded97c94a566f1605fef55899c81cc7682f
